### ISSUE TITLE
User Story 4 - Stationssuche

### ISSUE THREAD

**Issue by Rafhead** [SashkaHavr/motis#16]
Beschreibung: Als User kann ich die Stationssuchefelder verwenden, um die Station zu finden.

Akzeptanzkriterium: Bei der Texteingabe in die Felder "Start", "Ziel" oder ins Suchfeld oben rechts werden Vorschläge gemäß der Eingabe angeboten. Die Vorschläge enthalten immer 6 Stationen und 9 Adressen. Ein Vorschlag kann ausgewählt und ins entsprechende Feld übergeben werden. Design exakt wie im Original.

@felixguendling

**Comment by felixguendling** [comment]
Ergänzen: Design exakt wie im Original. In allen User Stories.
