### ISSUE TITLE
User Story 11 - Drag-and-Drop Funktion

### ISSUE THREAD

**Issue by Rafhead** [SashkaHavr/motis#39]
Beschreibung: Als Nutzer*in möchte ich die Möglichkeit haben, eine JSON Datei in das entsprechende Feld (Drag-and-Drop) zu bewegen.

Akzeptanzkriterium: Drag-and-Drop Feld befindet sich im Hauptfenster des linken Menus unter den Feldern "Ziel" und "Uhrzeit". Wird eine JSON Datei dem Drag-and-Drop Feld übermittelt, so werden danach die Connections entsprechend der Information in der JSON Datei ausgelesen und angezeigt. Nur die zu dem Connection Response Format passenden Dateien werden aufgenommen. 

@felixguendling

**Comment by SashkaHavr** [comment]
File for testing:
[responce2.txt](https://github.com/SashkaHavr/motis/files/7943703/responce2.txt)
