### ISSUE TITLE
User Story 12 - Anpassung der "Datum" und "Uhrzeit" Feldern für kleine Bildschirme

### ISSUE THREAD

**Issue by Rafhead** [SashkaHavr/motis#40]
Beschreibung: Als Nutzer*in möchte ich auf mobilen Endgeräten keine Pfeilen bei "Datum" und "Uhrzeit" Feldern ansehen und bei der Auswahl des Feldes "Uhrzeit" die Tastatur nur mit Ziffern haben.

Akzeptanzkriterium: Bei mobilen Engeräten werden die "Datum" und "Uhrzeit" Feldern ohne Pfeilen angezeigt, beim Auswahl des Feldes "Uhrzeit" wird die Tastatur nur mit Ziffern angezeigt.

@felixguendling

**Comment by SashkaHavr** [comment]
Number keyboard isn't shown on android devices
