### ISSUE TITLE
Implement McRaptor

### ISSUE THREAD

**Issue by Rafhead** [SashkaHavr/motis#60]
- [ ] Evaluate arameters in labels dominates()
- [ ] Intermodal module integration

**Comment by SashkaHavr** [comment]
![image](https://user-images.githubusercontent.com/47502748/176248740-82ebd09e-e723-4332-924f-ee2acce823d2.png)

**Comment by SashkaHavr** [comment]
be11dfd62c14884a784b213a98f891ab145a1f0f
892d1763c4461e6257e4f9aeee60f02ffe02f4a2

**Comment by SashkaHavr** [comment]
138f61b94e9c52d3bda710aa94f8114dba6dce4c
e98b3691afa9a58d2ae8205dbcf0e38b904b6676
67184bb9ddcd56d696b937e59aa0179eecb5f717

**Comment by SashkaHavr** [comment]
7a644d0b42410a6311db65a7354568ce14de3d0f

**Comment by SashkaHavr** [comment]
6c34de698342c09a5a80d81963eea58cd58c3b4c

**Comment by SashkaHavr** [comment]
d55dcf8faa37ee465b4f44d540b4459343417708

**Comment by SashkaHavr** [comment]
9cb13b611e3d53485ef42e60266fe2600f4d7ee4
74d13646f01ea9b9bd3938d9adbc2102001540fa
